[project]
channels = ["conda-forge"]
name = "Github Repo"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
streamlit = ">=1.25.0,<2"
requests = ">=2.32.3,<3"
geopandas = ">=1.0.1,<2"
rasterio = ">=1.4.3,<2"
numpy = ">=2.2.4,<3"
tqdm = ">=4.67.1,<5"
scipy = ">=1.15.2,<2"
gdal = ">=3.10.2,<4"
python = "3.11.*"
